name: Install and Commit Dependencies

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Specify Node.js version
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install additional dependencies
      # Optional: Add any additional dependency via a workflow input or edit directly
      run: |
        if [ -n "${{ github.event.inputs.package }}" ]; then
          npm install ${{ github.event.inputs.package }} --save
        fi

    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add package.json package-lock.json node_modules
        git status
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit."
        else
          git commit -m "Install dependencies and update package-lock.json"
          git push
        fi
