name: Generate Lock File and Add Dependencies

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  create-lock-file-and-install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Specify your Node.js version
        cache: 'npm'

    - name: Ensure package-lock.json exists
      run: |
        if [ ! -f package-lock.json ]; then
          echo "{}" > package-lock.json
          echo "Created an empty package-lock.json file."
        else
          echo "package-lock.json already exists."
        fi

    - name: Install dependencies
      run: npm install

    - name: Install Luxon
      run: npm install luxon --save

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add package-lock.json package.json
        git commit -m "Generate package-lock.json and add Luxon"
        git push
